plugins:
    - jekyll-paginate

paginate: 5
paginate_path: '/blog/:num/'

excerpt_separator: <!--more-->

date_format: '%-d %b %Y'

# safe: true

title: WriteGames.com
description: Learn about game development through articles, interviews, and interactive tutorials.
# timezone: America/Los_Angeles
sass:
    style: compressed
permalink: /:title

domain: beta.write.games
# domain: writegames.com
url: https://beta.write.games
# url: https://writegames.com
baseurl: /

collections:
    author:
        output: true
    history:
        output: true
    tag:
        output: true

defaults:
    - scope:
          path: ''
          type: 'author'
      values:
          layout: 'author'
    - scope:
          path: ''
          type: 'history'
      values:
          layout: 'history'
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author: 'bret-hudson'
    - scope:
          path: ''
      values:
          layout: 'default'
