plugins:
    - jekyll-paginate

paginate: 5
paginate_path: '/blog/:num/'

# safe: true

title: WriteGames.com
# timezone: America/Los_Angeles
sass:
    style: compressed
permalink: /:title

domain: writegames.github.io
url: https://writegames.github.io
baseurl: /beta-blog/

# domain: writegames.com
# url: https://writegames.com
# baseurl: /

collections:
    author:
        output: true
    history:
        output: true

defaults:
    - scope:
          path: ''
          type: 'author'
      values:
          layout: 'author'
    - scope:
          path: ''
          type: 'history'
      values:
          layout: 'history'
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author: 'bret-hudson'
    - scope:
          path: ''
      values:
          layout: 'default'
