plugins:
    - jekyll-paginate

paginate: 5
paginate_path: '/blog/:num/'

# safe: true

name: WriteGames.com
# timezone: America/Los_Angeles
sass:
    style: compressed
permalink: /:title

url: https://writegames.com
baseurl: /

collections:
    author:
        output: true

defaults:
    - scope:
          path: ''
          type: 'author'
      values:
          layout: 'author'
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author: 'bret-hudson'
    - scope:
          path: ''
      values:
          layout: 'default'
